---
abstract: 'unit test code that uses C<Net::Async::HTTP>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  HTTP::Request: '0'
  HTTP::Response: '0'
  Test::Identity: '0'
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Async-HTTP
provides:
  Test::Async::HTTP:
    file: lib/Test/Async/HTTP.pm
    version: '0.01'
  Test::Async::HTTP::Pending:
    file: lib/Test/Async/HTTP.pm
requires:
  Future: '0'
resources:
  IRC: irc://irc.perl.org/#io-async
  license: http://dev.perl.org/licenses/
version: '0.01'
